name: Packages

on:
  push:
    branches: [main]

jobs:
  publish-snapshot:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # https://github.com/yarnpkg/berry/issues/4014
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - run: yarn nx run-many -t build --projects="packages/*"

      - run: yarn workspaces foreach -At --no-private version 0.0.0-snapshot.$(git rev-parse --short HEAD) --immediate

      - run: scripts/publish.sh
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
